language: node_js
node_js:
- 6.9.5
before_install: npm install -g grunt-cli npm@'>=2.13.5'
install:
- npm install
before_script:
- grunt build
deploy:
  provider: npm
  email: ukfrontend@wonga.com
  api_key:
    secure: NFBuxmKD5FJfPu/SLRk7Ty1Y4AWqTTet1dbfQDqAoxl82d5D3EXK+PMXU/CxsMd9RyFsl/2B/+yGX+N7Oyt2uJs5YBxCaikTh2fZ1OdQj4yij/o264iw6+CtwHLObwtCmhk4t0XiuTRLQURj98BGpgsAUqyTtu59VOrN9cYg0gw=
